schemaVersion: 1
generatedAt: '2026-01-28T12:00:46.581Z'
summary:
  totalExcluded: 315
  wallet_provider: 171
  member_state: 43
  user_behavior: 2
  informative: 5
  multi_role_review: 32
  rulebook_author: 23
exclusions:
  wallet_provider:
    reason: Wallet Provider obligation - out of scope for RP/Issuer vendors
    hlrs:
      - DATA_DLT_01
      - DATA_DLT_02
      - DATA_DLT_02a
      - DATA_DLT_05
      - DATA_DLT_08
      - EDP_02
      - EDP_03
      - EDP_05
      - EDP_06
      - EDP_07
      - EDP_10
      - GenNot_01
      - GenNot_02
      - GenNot_05
      - ISSU_08
      - ISSU_09
      - ISSU_11
      - ISSU_11b
      - ISSU_12a
      - ISSU_12b
      - ISSU_13
      - ISSU_19
      - ISSU_19a
      - ISSU_20
      - ISSU_21
      - ISSU_23
      - ISSU_23a
      - ISSU_23b
      - ISSU_24
      - ISSU_24a
      - ISSU_28
      - ISSU_30
      - ISSU_33
      - ISSU_33a
      - ISSU_33b
      - ISSU_34
      - ISSU_34a
      - ISSU_35b
      - ISSU_36
      - ISSU_37
      - ISSU_38
      - ISSU_39
      - ISSU_40
      - ISSU_41
      - ISSU_42
      - ISSU_43
      - ISSU_44
      - ISSU_45
      - ISSU_46
      - ISSU_47
      - ISSU_48
      - ISSU_49
      - ISSU_51
      - ISSU_52
      - ISSU_53
      - ISSU_54
      - ISSU_55
      - ISSU_56a
      - ISSU_57
      - ISSU_57a
      - ISSU_58
      - ISSU_60
      - ISSU_61
      - ISSU_63
      - ISSU_64
      - ISSU_65
      - OIA_01
      - OIA_02
      - OIA_03b
      - OIA_03c
      - OIA_05
      - OIA_06
      - OIA_07
      - OIA_08
      - OIA_08a
      - OIA_08b
      - OIA_08d
      - OIA_08e
      - OIA_09
      - OIA_10
      - OIA_11
      - PA_01
      - PA_02
      - PA_03
      - PA_04
      - PA_05
      - PA_06
      - PA_07
      - PA_08
      - PA_08a
      - PA_09
      - PA_14
      - PA_16
      - PA_18
      - PA_19
      - PA_20
      - PA_22
      - ProxId_01
      - ProxId_02
      - ProxId_03
      - ProxId_04
      - ProxId_05
      - QES_01
      - QES_02
      - QES_03
      - QES_04
      - QES_05
      - QES_06
      - QES_07
      - QES_08
      - QES_10
      - QES_11
      - QES_12
      - QES_13
      - QES_14
      - QES_15
      - QES_16
      - QES_17
      - QES_18
      - QES_19
      - QES_23
      - QES_24
      - RPA_01a
      - RPA_04
      - RPA_06a
      - RPA_07a
      - RPA_10
      - RPA_10a
      - RPA_11
      - RPI_07a
      - RPRC_16
      - RPRC_17
      - RPRC_18
      - RPRC_20
      - RPRC_20a
      - RPRC_21
      - RPRC_23
      - TLPub_01
      - TLPub_02
      - TLPub_06
      - TLPub_08
      - VCR_06
      - VCR_07
      - VCR_10
      - VCR_16
      - VCR_17
      - VCR_18
      - WPNot_01
      - WPNot_02
      - WPNot_03
      - WPNot_04
      - WPNot_05
      - WPNot_06
      - WUA_01
      - WUA_02
      - WUA_03
      - WUA_05
      - WUA_05a
      - WUA_06
      - WUA_07
      - WUA_08
      - WUA_09
      - WUA_10
      - WUA_11
      - WUA_11b
      - WUA_12
      - WUA_14
      - WUA_16
      - WUA_17
      - WUA_18
      - WUA_20
  member_state:
    reason: Member State or Commission obligation - government responsibility
    hlrs:
      - RPA_02
      - PA_21
      - ARB_25
      - Reg_01a
      - Reg_02
      - Reg_03
      - Reg_04
      - Reg_06
      - Reg_07
      - Reg_09
      - Reg_10
      - Reg_11
      - Reg_19
      - Reg_20
      - Reg_20a
      - Reg_20b
      - Reg_21
      - Reg_22
      - Reg_22a
      - Reg_22b
      - Reg_24
      - Reg_25
      - Reg_26
      - Reg_29
      - GenNot_03
      - GenNot_04
      - PPNot_01
      - PPNot_05
      - PPNot_06
      - PuBPNot_01
      - PuBPNot_02
      - RPACANot_01
      - RPACANot_02
      - RPACANot_04
      - TLPub_07
      - QTSPAS_01
      - QTSPAS_06
      - QTSPAS_07
      - EDP_08
      - RPRC_01
      - RPRC_02
      - RPRC_09
      - RPRC_13
  user_behavior:
    reason: User action or choice - end-user behavior, not vendor implementation
    hlrs:
      - VCR_08
      - ISSU_27a
  informative:
    reason: Informative requirement - defines terms or provides context, not implementation
    hlrs:
      - PID_03
      - RPRC_04
      - RPRC_06
      - RPRC_07
      - RPRC_15
  multi_role_review:
    reason: Requires manual review - multi-role HLR
    hlrs:
      - RPA_12
      - VCR_07a
      - VCR_07b
      - VCR_14
      - ISSU_04
      - ISSU_10
      - ISSU_12c
      - ISSU_56
      - ISSU_62
      - ISSU_66
      - PA_12
      - ARB_07
      - ARB_08
      - ARB_15
      - ARB_17
      - ARB_19
      - ARB_21
      - ARB_26
      - ARB_27
      - ARB_29
      - ARB_31
      - ARB_32
      - QES_17a
      - QES_24a
      - Reg_16
      - Reg_18
      - RPACANot_05
      - TLPub_03
      - TLPub_04
      - TLPub_05
      - QTSPAS_07a
      - RPRC_08
  rulebook_author:
    reason: Rulebook or Scheme Provider obligation - defines standards, not vendor implementation
    hlrs:
      - ARB_01
      - ARB_01a
      - ARB_05
      - ARB_06
      - ARB_06a
      - ARB_09
      - ARB_11
      - ARB_13
      - ARB_14
      - ARB_16
      - ARB_18
      - ARB_20
      - ARB_22
      - ARB_23
      - ARB_24
      - ARB_30
      - ARB_33
      - ARB_34
      - ARB_28
      - ARB_01b
      - ARB_06b
      - ARB_10
      - ARB_12
